import { Kolory } from "../theme/kolory.slint";
import {
    MapaKanwa,
    MapaKokpit,
    MapaCelownik,
    MapaLogika,
    MapaWarstwyZiemi,
    MapaWarstwyDanych,
} from "../element/mapa.slint";
import { OknoSzkielet, OknoGuzik } from "../element/okno.slint";
import { LineEdit } from "std-widgets.slint";

export component AppGenetekaZakres inherits OknoSzkielet {
    preferred-width: 1600px;
    preferred-height: 1000px;
    window-title: "GENETEKA - CO JEST?";
    callback search(string);
    in property <image> map_frame;
    callback camera_changed(float, float, float, float, float, float);
    in-out property <[string]> search_results: [];
    in property <float> geo_min_lon;
    in property <float> geo_max_lon;
    in property <float> geo_min_lat;
    in property <float> geo_max_lat;
    in-out property <string> bbox_res: "50m";
    in-out property <string> coastline_res: "50m";
    in-out property <string> ocean_res: "none";
    in-out property <string> rivers_res: "none";
    in-out property <string> lakes_res: "none";
    in-out property <string> glaciers_res: "none";
    in-out property <string> graticules_30_res: "none";
    in-out property <string> graticules_10_res: "none";
    // Dostępne opcje: "brak", "z_mapy", "z_rejestru", "suma"
    in-out property <string> opracowane_parafie: "z_mapy"; // Na razie mamy tylko kropki z KML
    VerticalLayout {
        padding: 20px;
        spacing: 15px;
        HorizontalLayout {
            spacing: 10px;
            height: 40px;
            input := LineEdit {
                placeholder-text: "Szukaj parafii...";
                accepted => {
                    root.search(self.text);
                }
            }

            OknoGuzik {
                text: "SZUKAJ";
                width: 100px;
                primary: true;
                clicked => {
                    root.search(input.text);
                }
            }
        }

        kanwa := MapaKanwa {
            map_frame: root.map_frame;
            camera_changed(w, h, ox, oy, z, rot) => {
                root.camera_changed(w, h, ox, oy, z, rot);
            }
            MapaCelownik {
                width: 100%;
                height: 100%;
                n_coord: MapaLogika.current_lat(kanwa.width, kanwa.height, kanwa.map_offset_x, kanwa.map_offset_y, kanwa.map_zoom, kanwa.map_rotation, root.geo_min_lat, root.geo_max_lat);
                e_coord: MapaLogika.current_lon(kanwa.width, kanwa.height, kanwa.map_offset_x, kanwa.map_offset_y, kanwa.map_zoom, kanwa.map_rotation, root.geo_min_lon, root.geo_max_lon);
                zoom_str: MapaLogika.current_zoom(kanwa.map_zoom);
                rot_str: MapaLogika.current_rot(kanwa.map_rotation);
                anchor: "ne";
            }

            MapaKokpit {
                anchor: "sw";
                margin: 10px;
                x: (self.anchor == "nw" || self.anchor == "sw") ? self.margin : parent.width - self.width - self.margin;
                y: (self.anchor == "nw" || self.anchor == "ne") ? self.margin : parent.height - self.height - self.margin;
                zoom_in => {
                    kanwa.zoom_around_center(kanwa.map_zoom * 1.15);
                }
                zoom_out => {
                    kanwa.zoom_around_center(kanwa.map_zoom / 1.15);
                }
                rotate_ccw => {
                    kanwa.rotate_view(-5deg);
                }
                rotate_cw => {
                    kanwa.rotate_view(5deg);
                }
                pan(dx, dy) => {
                    kanwa.map_offset_x += dx;
                    kanwa.map_offset_y += dy;
                    kanwa.trigger_render();
                }
                reset => {
                    kanwa.map_zoom = 1.0;
                    kanwa.map_offset_x = 0px;
                    kanwa.map_offset_y = 0px;
                    kanwa.map_rotation = 0deg;
                    kanwa.trigger_render();
                }
            }

            MapaWarstwyZiemi {
                margin: 10px;
                x: parent.width - self.width - self.margin;
                y: parent.height - self.height - self.margin;
                
                // Dowiązanie dwukierunkowe!
                bbox_res <=> root.bbox_res;
                coastline_res <=> root.coastline_res;
                ocean_res <=> root.ocean_res;
                rivers_res <=> root.rivers_res;
                lakes_res <=> root.lakes_res;
                glaciers_res <=> root.glaciers_res;
                graticules_30_res <=> root.graticules_30_res;
                graticules_10_res <=> root.graticules_10_res;
                warstwy_zmienione => {
                    kanwa.trigger_render();
                }
            }

            MapaWarstwyDanych {
                margin: 10px;
                x: parent.width - self.width - self.margin - 40px;
                y: parent.height - self.height - self.margin;
                
                // Dowiązanie dwukierunkowe!
                opracowane_parafie <=> root.opracowane_parafie;
                warstwy_zmienione => {
                    kanwa.trigger_render();
                }
            }
        }
    }
}
