import { Kolory } from "../theme/kolory.slint";
import { OknoSzkielet, OknoGuzik } from "../element/okno.slint";
import { LineEdit, ScrollView } from "std-widgets.slint";

export component AppKartezjanProdukt inherits OknoSzkielet {
    preferred-width: 600px;
    preferred-height: 300px;
    window-title: "CPSGen - FORMATOWANIE";
    in-out property <[string]> results: [];
    in-out property <string> joined_text: "";
    in-out property <bool> show_as_list: true;
    callback send(string);
    callback copy_to_clipboard(string);
    VerticalLayout {
        padding: 20px;
        spacing: 15px;
        alignment: start;
        input := LineEdit {
            placeholder-text: "Wzór...";
            height: 35px;
            accepted => {
                root.send(self.text);
            }
        }

        HorizontalLayout {
            spacing: 10px;
            height: 35px;
            OknoGuzik {
                text: "LISTA";
                enabled: !root.show_as_list;
                clicked => {
                    root.show_as_list = true;
                }
            }

            OknoGuzik {
                text: "TEKST";
                enabled: root.show_as_list;
                clicked => {
                    root.show_as_list = false;
                }
            }
        }

        OknoGuzik {
            text: "GENERUJ";
            height: 40px;
            primary: true;
            clicked => {
                root.send(input.text);
            }
        }

        Rectangle {
            background: Kolory.background-light;
            border-radius: 4px;
            vertical-stretch: 1;
            clip: true;
            ScrollView {
                viewport-width: self.width;
                if (root.show_as_list): VerticalLayout {
                    padding: 10px;
                    spacing: 5px;
                    for res in root.results: Text {
                        text: res;
                        color: Kolory.accent-success;
                    }
                }
                if (!root.show_as_list): VerticalLayout {
                    padding: 10px;
                    Text {
                        text: root.joined_text;
                        color: Kolory.accent-success;
                        wrap: word-wrap;
                    }
                }
            }
        }

        OknoGuzik {
            text: "KOPIUJ WYNIKI";
            clicked => {
                root.copy_to_clipboard(root.show_as_list ? "list" : "text");
            }
        }
    }
}
