import { Button, ScrollView, LineEdit } from "std-widgets.slint";
import { Palette } from "globals.slint";

export component AppWindow inherits Window {
    no-frame: true;
    background: transparent;
    width: 500px;
    height: 700px;
    in-out property <[string]> results: [];
    in-out property <string> joined_text: "";
    in-out property <bool> show_as_list: true;
    callback quit();
    callback send(string);
    callback move_window(length, length);
    Rectangle {
        width: 100%;
        height: 100%;
        background: Palette.background;
        border-radius: 12px;
        border-width: 2px;
        border-color: Palette.accent-success; // Zielona obwódka z Palette
        clip: true;
        VerticalLayout {
            // Pasek Drag
            Rectangle {
                height: 50px;
                background: Palette.title-bar-background;
                Text {
                    text: "CPSGen - WYBÓR FORMATU";
                    color: Palette.text-primary;
                }

                TouchArea {
                    pointer-event(event) => {
                        if (event.kind == PointerEventKind.down && event.button == PointerEventButton.left) {
                            root.move_window(0px, 0px);
                        }
                    }
                }
            }

            VerticalLayout {
                padding: 20px;
                spacing: 15px;
                alignment: start;
                input := LineEdit {
                    placeholder-text: "Wzór...";
                    height: 35px;
                    accepted => {
                        root.send(self.text);
                    }
                }

                HorizontalLayout {
                    spacing: 10px;
                    height: 35px;
                    Button {
                        text: "WIDOK LISTY";
                        enabled: !root.show_as_list;
                        clicked => {
                            root.show_as_list = true;
                        }
                    }

                    Button {
                        text: "WIDOK TEKSTU";
                        enabled: root.show_as_list;
                        clicked => {
                            root.show_as_list = false;
                        }
                    }
                }

                Button {
                    text: "GENERUJ";
                    height: 40px;
                    primary: true;
                    clicked => {
                        root.send(input.text);
                    }
                }

                Rectangle {
                    background: Palette.background-light;
                    border-radius: 4px;
                    vertical-stretch: 1;
                    clip: true;
                    ScrollView {
                        viewport-width: self.width;
                        if (root.show_as_list): VerticalLayout {
                            padding: 10px;
                            spacing: 5px;
                            alignment: start;
                            for res in root.results: Text {
                                text: res;
                                color: Palette.accent-success; // Wyniki na zielono
                            }
                        }
                        if (!root.show_as_list): VerticalLayout {
                            padding: 10px;
                            Text {
                                text: root.joined_text;
                                color: Palette.accent-success; // Wyniki na zielono
                                wrap: word-wrap;
                            }
                        }
                    }
                }

                Button {
                    text: "ZAMKNIJ";
                    clicked => {
                        root.quit();
                    }
                }
            }
        }
    }
}
