import { Kolory } from "../theme/kolory.slint";
import { OknoGranica } from "okno-granica.slint";
import { OknoLogika } from "okno-logika.slint";
import { OknoPasek } from "okno-pasek.slint";

export component OknoSzkielet inherits Window {
    no-frame: true;
    background: transparent;
    min-width: 200px;
    min-height: 50px;
    in property <string> window-title: "TYTUŁ OKNA";
    Rectangle {
        width: 100%;
        height: 100%;
        background: Kolory.window-backgr-box;
        border-radius: 12px;
        border-width: 2px;
        border-color: Kolory.window-border-box;
        clip: true;
        VerticalLayout {
            OknoPasek {
                window-title: root.window-title;
            }

            Rectangle {
                vertical-stretch: 1;
                @children
            }
        }

        OknoGranica {
            resize(dir) => {
                OknoLogika.wymiarowanie(dir);
            }
        }
    }
}
